[package]
name = "tictaxtoe_client"
version = "0.1.0"
authors = ["JesseBadry <jessebadry@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jb_utils={git="https://github.com/jessebadry/jb_utils.git"}